// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Infrastructure.Database;

#nullable disable

namespace WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.ProjectAggregate.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.TicketAggregate.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("CompletionCriteria")
                        .HasColumnType("text")
                        .HasColumnName("completion_criteria");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_assignee_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_tickets_project_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.HasOne("WebApi.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId")
                                .HasConstraintName("fk_notifications_notifications_id");
                        });

                    b.OwnsOne("WebApi.Domain.Aggregates.NotificationAggregate.NotificationCategory", "Category", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("category");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId")
                                .HasConstraintName("fk_notifications_notifications_id");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Category")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.ProjectAggregate.Project", b =>
                {
                    b.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.OwnsMany("WebApi.Domain.Aggregates.ProjectAggregate.ProjectMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("ProjectId", "Id")
                                .HasName("pk_project_member");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_project_member_user_id");

                            b1.ToTable("project_member", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_project_member_projects_project_id");

                            b1.HasOne("WebApi.Domain.Aggregates.UserAggregate.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_project_member_users_user_id");

                            b1.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b2 =>
                                {
                                    b2.Property<Guid>("ProjectMemberProjectId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("project_id");

                                    b2.Property<Guid>("ProjectMemberId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<Guid>("CreatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("created_by");

                                    b2.Property<DateTime>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_at");

                                    b2.Property<Guid>("UpdatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("updated_by");

                                    b2.HasKey("ProjectMemberProjectId", "ProjectMemberId");

                                    b2.ToTable("project_member");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectMemberProjectId", "ProjectMemberId")
                                        .HasConstraintName("fk_project_member_project_member_project_id_id");
                                });

                            b1.OwnsOne("WebApi.Domain.Aggregates.ProjectAggregate.ProjectRole", "Role", b2 =>
                                {
                                    b2.Property<Guid>("ProjectMemberProjectId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("project_id");

                                    b2.Property<Guid>("ProjectMemberId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("role");

                                    b2.HasKey("ProjectMemberProjectId", "ProjectMemberId");

                                    b2.ToTable("project_member");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectMemberProjectId", "ProjectMemberId")
                                        .HasConstraintName("fk_project_member_project_member_project_id_id");
                                });

                            b1.Navigation("AuditInfo")
                                .IsRequired();

                            b1.Navigation("Role")
                                .IsRequired();
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.TicketAggregate.Ticket", b =>
                {
                    b.HasOne("WebApi.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_assignee_id");

                    b.HasOne("WebApi.Domain.Aggregates.ProjectAggregate.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.OwnsMany("WebApi.Domain.Aggregates.TicketAggregate.AssignmentHistory", "AssignmentHistories", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("AssigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignee_id");

                            b1.Property<int>("ChangeType")
                                .HasColumnType("integer")
                                .HasColumnName("change_type");

                            b1.Property<DateTime>("ChangedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at");

                            b1.Property<Guid?>("PreviousAssigneeId")
                                .HasColumnType("uuid")
                                .HasColumnName("previous_assignee_id");

                            b1.HasKey("TicketId", "Id")
                                .HasName("pk_assignment_histories");

                            b1.ToTable("assignment_histories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_assignment_histories_tickets_ticket_id");

                            b1.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b2 =>
                                {
                                    b2.Property<Guid>("AssignmentHistoryTicketId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("ticket_id");

                                    b2.Property<Guid>("AssignmentHistoryId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<Guid>("CreatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("created_by");

                                    b2.Property<DateTime>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_at");

                                    b2.Property<Guid>("UpdatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("updated_by");

                                    b2.HasKey("AssignmentHistoryTicketId", "AssignmentHistoryId");

                                    b2.ToTable("assignment_histories");

                                    b2.WithOwner()
                                        .HasForeignKey("AssignmentHistoryTicketId", "AssignmentHistoryId")
                                        .HasConstraintName("fk_assignment_histories_assignment_histories_ticket_id_id");
                                });

                            b1.Navigation("AuditInfo")
                                .IsRequired();
                        });

                    b.OwnsOne("WebApi.Domain.Aggregates.TicketAggregate.Deadline", "Deadline", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("deadline");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_id");
                        });

                    b.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_id");
                        });

                    b.OwnsMany("WebApi.Domain.Aggregates.TicketAggregate.TicketComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("content");

                            b1.HasKey("TicketId", "Id")
                                .HasName("pk_ticket_comments");

                            b1.ToTable("ticket_comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                            b1.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b2 =>
                                {
                                    b2.Property<Guid>("TicketCommentTicketId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("ticket_id");

                                    b2.Property<Guid>("TicketCommentId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<Guid>("CreatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("created_by");

                                    b2.Property<DateTime>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_at");

                                    b2.Property<Guid>("UpdatedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("updated_by");

                                    b2.HasKey("TicketCommentTicketId", "TicketCommentId");

                                    b2.ToTable("ticket_comments");

                                    b2.WithOwner()
                                        .HasForeignKey("TicketCommentTicketId", "TicketCommentId")
                                        .HasConstraintName("fk_ticket_comments_ticket_comments_ticket_id_id");
                                });

                            b1.Navigation("AuditInfo")
                                .IsRequired();
                        });

                    b.OwnsOne("WebApi.Domain.Aggregates.TicketAggregate.TicketStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_id");
                        });

                    b.OwnsOne("WebApi.Domain.Aggregates.TicketAggregate.TicketTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_id");
                        });

                    b.Navigation("AssignmentHistories");

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Deadline");

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("WebApi.Domain.Aggregates.UserAggregate.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("WebApi.Domain.Aggregates.UserAggregate.SystemRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("WebApi.Domain.Common.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
