name: CI

on:
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  backend_ci_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup ASP.NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: dotnet test ./WebApi.sln --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate summary
        run: |
          reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:coveragereport \
            -reporttypes:"MarkdownSummaryGithub"

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coveragereport/SummaryGithub.md

      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coveragereport/SummaryGithub.md
