name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup ASP.NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests with coverage
        run: |
          dotnet test tests/WebApi.Domain.Tests --no-build --configuration Release --collect:"XPlat Code Coverage"
          dotnet test tests/WebApi.Application.Tests --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate summary
        run: |
          reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:coveragereport \
            -reporttypes:"MarkdownSummaryGithub"

      - name: Publish Coverage to Job Summary
        run: |
          echo "## 📊 Unit Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

  integration_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup ASP.NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Integration Tests
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=postgres"
        run: dotnet test tests/WebApi.IntegrationTests --no-build --configuration Release
